web/router.ex
defmodule Cronweb.Router do
  use Phoenix.Router

  get "/", Cronweb.PageController, :index, as: :pages
  resources "/cronjobs", Cronweb.CronJobController
  #put "/cronjobs/:id"
end

web/models/backend.ex
defmodule Cronweb.Backend do
  @backend_name :agent_backend

  # Client API

  def get(document_id) do
    Agent.get(@backend_name, &HashDict.get(&1, document_id))
  end

  def get() do
    IO.inspect Agent.get(@backend_name, &HashDict.values(&1))
  end
  

  def insert(document, id_field_name) when is_atom(id_field_name) do
    id = Crypto.unique_id
    doc = Map.put document, id_field_name, id
    :ok = Agent.update(@backend_name, &HashDict.put(&1, id, doc))
    id
  end

  def insert(document, id_field_name) do
    insert(document, String.to_atom(id_field_name))
  end
  
  def update(document, id) do
    Agent.update(@backend_name, &HashDict.put(&1, id, document))
  end

  def delete(document_id) do
    Agent.get_and_update(@backend_name, &HashDict.pop(&1, document_id))
  end
  
  ##-------------------------------------------------
  ## Server/Agent Callbacks
  ##-------------------------------------------------

  def start_link do
    Agent.start_link(fn -> HashDict.new end, [name: @backend_name])
  end

end

web/models/cron_job.ex
defmodule Cronweb.CronJob do
  
  defstruct name: "",
     description: "",
   cron_schedule: "",
         command: "",
              id: "",
           class: "Cron",
         version:  0,
          active: false
  
end

web/models/cron_wrapper.ex
defmodule Cronweb.CronWrapper do

  @spec start_cron_job(String.t, String.t, String.t) :: {:ok, pid()} | {:error, any}
  def start_cron_job(id, cron_string, command) do
    schedule = {:cron, parse_cron_string(cron_string)}
    mfargs = {&__MODULE__.trigger_job/2, [id, command]}
    :leader_cron.schedule_task(id, schedule, mfargs)
  end

  def stop_cron_job(id) do
    :leader_cron.cancel_task(id)
  end

  def trigger_job(id, command) do
    IO.puts "Job #{id} triggered with command: #{command}"
  end

  def valid?(cron_string) do
    is_tuple(parse_cron_string(cron_string))
  end
  
  
  def parse_cron_string(cron_string) do
    cron_string
    |> String.split
    |> convert_tokens
  end

  defp convert_tokens(tokens) when length(tokens) == 5 do
    tokens    
    |> Enum.map(&translate_token(&1))
    |> List.to_tuple
  end

  defp convert_tokens(_), do: raise InvalidNumberOfTokensError

  defp translate_token("*"), do: :all
  defp translate_token(token) do
    cond do
      String.match?(token, ~r/\d+-\d+/) ->
        translate_token(:range, token)
      String.match?(token, ~r/(\d+,)+\d+/) ->
        translate_token(:list, token)
      String.match?(token, ~r/\d+/) -> translate_token(:num, token)
      true -> raise InvalidTokenError
    end
  end

  defp translate_token(:range, token) do
    [h|t] = String.split(token, ~r/-/, trim: true)
    |> Enum.map(&String.to_integer(&1))
    h..hd(t)
  end

  defp translate_token(:list, token) do
    String.split(token, ~r/,/, trim: true)
    |> Enum.map(&String.to_integer(&1))
  end

  defp translate_token(:num, token) do
    String.to_integer(token)
  end
  
end

defmodule InvalidNumberOfTokensError do
   defexception message: "Invalid number of cron tokens. Expected 5."
end

defmodule InvalidTokenError do
  defexception message: "Invalid token. Expected one of: num|*|num,num[...]|num-num"
end

web/controllers/cron_job_controller.ex
defmodule Cronweb.CronJobController do
  use Phoenix.Controller
  
  alias Cronweb.Router
  alias Cronweb.CronJob
  alias Cronweb.Backend

  def index(conn, _params) do
    redirect conn, Router.Helpers.pages_path(:index)
  end

  def new(conn, _params) do
    render conn, "new"
  end

  def create(conn, params) do
    cron_job = %CronJob{name: params["name"], 
          description: params["description"],
              command: params["command"],
              cron_schedule: params["cron_schedule"] }
    Backend.insert(cron_job, "id")
    redirect conn, Router.Helpers.pages_path(:index)
  end

  def show(conn, params) do
    IO.inspect params
    cron_job = Backend.get(params["id"])
    render conn, "cron_job", cron_job: cron_job, action: params["action"]
  end
  
  def edit(conn, params) do
    IO.puts "in edit"
    id = params["id"]
    cron_job = Backend.get(id)
    active = String.to_existing_atom(params["active"])
    IO.puts "active is #{active}, db is #{cron_job.active}"
    if (active != cron_job.active) do
      IO.puts "in if"
      cron_job = %{cron_job | active: active}
      Backend.update(cron_job, id)
      result = toggle_cron_job(cron_job, active)
      case result do
        :ok -> :ok
        _ ->
          cron_job = %{cron_job | active: not active}
          Backend.update(cron_job, id)
          IO.puts "cron toggle failed with #{to_string(elem(result, 1))}"
      end
      redirect conn, Router.Helpers.pages_path(:index)
    else
      render conn, "edit", cron_job: cron_job
    end
  end

  def update(conn, params) do
    #IO.inspect
    params = Dict.delete(params, "_method")
    cron_job = %CronJob{}

    cron_job = %{cron_job | name: params["name"],
        description: params["description"],
        command: params["command"],
        cron_schedule: params["cron_schedule"],
        id: params["id"],
        version: String.to_integer(params["version"]),
        active: String.to_existing_atom(params["active"])
      }

    Backend.update(cron_job, params["id"])
    
    redirect conn, Router.Helpers.pages_path(:index)
  end
  
  def destroy(conn, params) do
    Backend.delete(params["id"])
    redirect conn, Router.Helpers.pages_path(:index)
  end

  defp toggle_cron_job(cron_job, false) do
    Cronweb.CronWrapper.stop_cron_job(cron_job.id)
  end

  defp toggle_cron_job(cron_job, true) do
    #IO.puts "inside toggle_cron_job false"
    result = Cronweb.CronWrapper.start_cron_job(cron_job.id,
      cron_job.cron_schedule,
      cron_job.command)
    case result do
      {:ok, _pid} -> :ok
      _ -> result
    end
  end
end

web/controllers/page_controller.ex
defmodule Cronweb.PageController do
  use Phoenix.Controller

  def index(conn, _params) do
    cron_jobs = Cronweb.Backend.get
    render conn, "index", [cron_jobs: cron_jobs]
  end

  def not_found(conn, _params) do
    render conn, "not_found"
  end

  def error(conn, _params) do
    render conn, "error"
  end
end

web/views/cron_job_view.ex
defmodule Cronweb.CronJobView do
  use Cronweb.Views
  
end

web/views/layout_view.ex
defmodule Cronweb.LayoutView do
  use Cronweb.Views

end

web/views/page_view.ex
defmodule Cronweb.PageView do
  use Cronweb.Views

end

web/templates/cron_job/cron_job.html.eex
<div class="row">

  <div class="col-md-12">
    <%= if @action == "delete" do %>
    <h2>Are you sure you want to delete <%= @cron_job.name %>??</h2>
    <%= else %>
    <h2><%= @cron_job.name %></h2>
    <%= end %>
    <h4>
      <span class="label label-success">
        <%= @cron_job.cron_schedule %>
      </span> &nbsp;
      <span class="label label-default">
        <%= @cron_job.command %>
      </span>
    </h4>
  </div>

  <div class="col-md-12">
    <p>
    <%= @cron_job.description %>
    </p>
  </div>

  <div class="col-md-12">
    <form action="<%= cron_job_path(:destroy, @cron_job.id) %>" method="post">
    <input type="hidden" name="version" value="<%= @cron_job.version %>">
    <a href="/" class="btn btn-success">Back</a>
    <%= if @action == "delete" do %>
      <input type="hidden" name="_method" value="DELETE">
      <!-- <input type="hidden" name="id" value="<%= @cron_job.id %>"> -->
      <button type="submit" class="btn btn-danger pull-right">Delete</button>
    <%= end %>
    </form>
  </div>

</div>

web/templates/cron_job/edit.html.eex
<h2>Edit Job</h2>
<form class="form-horizontal" action="/cronjobs/<%= @cron_job.id %>" method="post">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Job Name</label>
    <div class="col-sm-10">
      <input type="hidden" name="_method" value="PATCH">
      <input type="hidden" name="version" value="<%= @cron_job.version %>">
      <input type="text" class="form-control" value="<%= @cron_job.name %>" name="name" placeholder="Job Name" required="required">
    </div>
  </div>

  <div class="form-group">
    <label for="description" class="col-sm-2 control-label">Job Description</label>
    <div class="col-sm-10">
      <textarea id="description" placeholder="Job description..." class="form-control" name="description" cols="30" rows="10" required="required"><%= @cron_job.description %></textarea>
    </div>
  </div>

  <div class="form-group">
    <label for="cron_schedule" class="col-sm-2 control-label">Job Schedule</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="cron_schedule" id="cron_schedule" value="<%= @cron_job.cron_schedule %>" placeholder="Job Schedule">
    </div>
  </div>
  <div class="form-group">
    <label for="command" class="col-sm-2 control-label">Command</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="command" placeholder="Command" value="<%= @cron_job.command %>">
      <input type="hidden" name="active" value="<%= @cron_job.active %>">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-warning">Update</button>
    </div>
  </div>
</form>

web/templates/cron_job/new.html.eex
<div class="row">
  <div class="col-lg-12">
    <h1>New Job</h1>
    <form class="form-horizontal" method="post" action="/cronjobs" name="newJob">

      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Job Name</label>
        <div class="col-sm-10">
          <input id="name" name="name" type="text" class="form-control" placeholder="Job Name" required="required">
        </div>
      </div>

      <div class="form-group">
        <label for="description" class="col-sm-2 control-label">Job Description</label>
        <div class="col-sm-10">
          <textarea id="description" placeholder="Job description..." class="form-control" name="description" cols="30" rows="4" required="required"></textarea>
        </div>
      </div>

      <div class="form-group">
        <label for="schedule" class="col-sm-2 control-label">Job Schedule</label>
        <div class="col-sm-10">
          <input id="schedule" name="cron_schedule" type="text" class="form-control" placeholder="Job Schedule">
        </div>
      </div>
      <div class="form-group">
        <label for="command" class="col-sm-2 control-label">Job Command</label>
        <div class="col-sm-10">
          <input id="command" name="command" type="text" class="form-control" placeholder="Job Command">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-warning">Save</button>
        </div>
      </div>

    </form>
  </div>

</div>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="/css/app.css">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="https://github.com/phoenixframework/phoenix">Get Started</a></li>
        </ul>
        <span class="logo"></span>
      </div>

      <%= @inner %>

      <div class="footer">
        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
      </div>

    </div> <!-- /container -->
  </body>
</html>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/index.html.eex
<div class="row">
  <div class="col-md-4">
    <h2>Cron Jobs</h2>
  </div>
  <div class="col-md-8" style="text-align: right">
    <a href="<%= cron_job_path(:new)%>" class="btn btn-danger">New cron job</a>
  </div>
</div>
<ul class="list-unstyled" style="">
  <%= for cron_job <- @cron_jobs do %>
  <li class="job-list">
    <div class="row">
      <div class="col-md-8">
        <a href="/cronjobs/<%= cron_job.id %>">
          <span class="title"><%= cron_job.name %></span>
          <span class="label label-success"><%= cron_job.cron_schedule %></span>
          <span class="label label-default"><%= cron_job.command %></span>
        </a>
      </div>
      <div class="col-md-4 buttons" style="text-align: right">
      <%= if cron_job.active == true do %>
        <a href="/cronjobs/<%= cron_job.id %>/edit?active=false" class="btn btn-success btn-sm">
          Stop</a> &nbsp;&nbsp;
      <% else %>
        <a href="/cronjobs/<%= cron_job.id %>/edit?active=true" class="btn btn-danger btn-sm">
          Start</a> &nbsp;&nbsp;
      <% end %>
        <a href="/cronjobs/<%= cron_job.id %>/edit" class="btn btn-warning btn-sm">
          Edit</a> &nbsp;&nbsp;
          <a href="/cronjobs/<%= cron_job.id %>?action=delete" class="btn btn-default btn-sm">
            Delete</a>
<!--          <input type="hidden" name="_method" value="DELETE">
          <button type="submit" class="btn btn-default btn-sm">Delete</button>
        -->
      </div>
    </div>
  </li>
  <% end %>
</ul>

web/templates/page/not_found.html.eex
The page you are looking for does not exist